language: node_js
cache:
  directories:
    - ./node_modules
  node_js:
    - "13"
  before_install:
  - npm install -g yarn
  - yarn
  script:
  - yarn run build
  - yarn test
  deploy:
    provider: script
    script: yarn && yarn run deploy
    skip_cleanup: true
    on:
      branch: gh-pages